version: '3.9'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    restart: always
  app:
    build: .
    command: uwsgi --ini ./uwsgi.ini
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: mysite
      MYSQL_DATABASE: mysite
      MYSQL_USER: mysite
      MYSQL_PASSWORD: mysite
    volumes:
      - db-data:/var/lib/mysql/
    ports:
      - "3306:3306"
    restart: always
volumes:
  db-data:
    driver: local
