version: '3.9'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    restart: always
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - db-data:/var/lib/mysql/
    ports:
      - "3306:3306"
    restart: always
volumes:
  db-data:
    driver: local
